---
title: Shihab Uddin Alvi
logo: images/headshot1.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
---

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page.title }}</title>
  <style>
    /* Reset CSS */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    /* Global Styles */
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      background-color: #f8f8f8;
      color: #333;
    }

    header {
      background-color: #54403B;
      color: #fff;
      padding: 20px;
      text-align: center;
    }

    .logo img {
      width: 100px;
      height: auto;
    }

    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 20px;
    }

    section {
      padding: 40px 0;
      text-align: center;
    }

    h2 {
      font-size: 2em;
      margin-bottom: 20px;
    }

    footer {
      background-color: #54403B;
      color: #fff;
      text-align: center;
      padding: 20px 0;
      position: fixed;
      width: 100%;
      bottom: 0;
    }
  </style>
</head>
<body>
  <header>
    <div class="logo">
      <img src="{{ page.logo }}" alt="Shihab Uddin Alvi Logo">
    </div>
    <h1>{{ page.title }}</h1>
  </header>

  <section id="about">
    <div class="container">
      <h2>About Me</h2>
      <div class="about-content">
        <img src="{{ page.logo }}" alt="Shihab Uddin Alvi">
        <p>Welcome to my portfolio website! I'm Shihab Uddin Alvi, a passionate web developer with a keen interest in creating stunning and user-friendly websites.</p>
      </div>
    </div>
  </section>

  <!-- Add more sections for portfolio and contact as needed -->

  <footer>
    <div class="container">
      <p>&copy; 2024 Shihab Uddin Alvi. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>
