/* Reset CSS */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

/* Global Styles */
body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  margin-top: 100px; /* Add margin-top to avoid overlapping with the header */
}

.container {
  max-width: 960px;
  margin: 0 auto;
  padding: 0 20px;
}

header {
  background-color: #333;
  color: #fff;
  padding: 20px 0;
  position: fixed; /* Make the header fixed for easy navigation */
  width: 100%;
  top: 0;
  z-index: 1000; /* Ensure the header is above other elements */
}

nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo img {
  width: 100px;
  height: auto;
}

.menu ul {
  list-style-type: none;
}

.menu ul li {
  display: inline;
  margin-right: 20px;
}

.menu ul li a {
  color: #fff;
  text-decoration: none;
}

section {
  padding: 60px 0;
}

h2 {
  font-size: 2em;
  margin-bottom: 30px;
}

.about-content {
  display: flex;
  align-items: center;
}

.about-content img {
  width: 200px;
  border-radius: 50%;
  margin-right: 20px;
  position: absolute; /* Position the image absolutely within the header */
  top: 20px; /* Adjust top position as needed */
  left: 20px; /* Adjust left position as needed */
}

/* Add more styles for portfolio items and contact form as needed */

footer {
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 20px 0;
}
