<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shihab Uddin Alvi</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <nav>
      <div class="logo">
        <img src="images/headshot1.png" alt="Shihab Uddin Alvi Logo">
      </div>
      <div class="menu">
        <ul>
          <li><a href="#about">About</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </nav>
  </header>

  <section id="about">
    <div class="container">
      <h2>About Me</h2>
      <div class="about-content">
        <img src="images/headshot1.png" alt="Shihab Uddin Alvi">
        <p>Welcome to my portfolio website! I'm Shihab Uddin Alvi, a passionate web developer with a keen interest in creating stunning and user-friendly websites.</p>
      </div>
    </div>
  </section>

  <section id="portfolio">
    <div class="container">
      <h2>Portfolio</h2>
      <div class="portfolio-items">
        <!-- Your portfolio items go here -->
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <h2>Contact Me</h2>
      <div class="contact-form">
        <!-- Your contact form goes here -->
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; 2024 Shihab Uddin Alvi. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>
