<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shihab Uddin Alvi</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <nav>
      <div class="logo">
        <img src="images/headshot1.png" alt="Shihab Uddin Alvi Logo">
      </div>
      <div class="menu">
        <ul>
          <li><a href="#about">About</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </nav>
  </header>

  <section id="about">
    <div class="container">
      <h2>About Me</h2>
      <div class="about-content">
        <img src="images/headshot1.png" alt="Shihab Uddin Alvi">
        <p>Welcome to my portfolio website! I'm Shihab Uddin Alvi, a passionate web developer with a keen interest in creating stunning and user-friendly websites.</p>
      </div>
    </div>
  </section>

  <section id="portfolio">
    <div class="container">
      <h2>Portfolio</h2>
      <div class="portfolio-items">
        <!-- Your portfolio items go here -->
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <h2>Contact Me</h2>
      <div class="contact-form">
        <!-- Your contact form goes here -->
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; 2024 Shihab Uddin Alvi. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>

/* Reset CSS */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

/* Global Styles */
body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  padding: 0 20px;
}

header {
  background-color: #333;
  color: #fff;
  padding: 20px 0;
}

nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo img {
  width: 100px;
  height: auto;
}

.menu ul {
  list-style-type: none;
}

.menu ul li {
  display: inline;
  margin-right: 20px;
}

.menu ul li a {
  color: #fff;
  text-decoration: none;
}

section {
  padding: 60px 0;
}

h2 {
  font-size: 2em;
  margin-bottom: 30px;
}

.about-content {
  display: flex;
  align-items: center;
}

.about-content img {
  width: 200px;
  border-radius: 50%;
  margin-right: 20px;
}

/* Add more styles for portfolio items and contact form as needed */

footer {
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 20px 0;
}
